const TOGGLE_CART = "TOGGLE_CART";
const TOGGLE_BURGER = "TOGGLE_BURGER";
const HANDLE_SEARCH = "HANDLE_SEARCH";
const CLEAR_SEARCH = "CLEAR_SEARCH";
const FOCUSE_SEARCH = "FOCUSE_SEARCH";
const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
const TOGGLE_AUTH_MODAL = "TOGGLE_AUTH_MODAL";
const FETCH_USER_VK_INFO = "FETCH_USER_VK_INFO,";
const FILTER_RESTAURANTS = "FILTER_RESTAURANTS";
const FETCH_RESTAURANT_CATEGORIES = "FETCH_RESTAURANT_CATEGORIES";
const SELECT_CATEGORY_ID = "SELECT_CATEGORY_ID";
const FETCH_RESTAURANT_PRODUCTS = "FETCH_RESTAURANT_PRODUCTS";
const TOGGLE_PRODUCT_MODAL = "TOGGLE_PRODUCT_MODAL";
const SELECT_PRODUCT = "SELECT_PRODUCT";
const appActions = {
  TOGGLE_CART,
  TOGGLE_BURGER,
  HANDLE_SEARCH,
  CLEAR_SEARCH,
  FOCUSE_SEARCH,
  FETCH_RESTAURANTS,
  TOGGLE_AUTH_MODAL,
  FETCH_USER_VK_INFO,
  FILTER_RESTAURANTS,
  FETCH_RESTAURANT_CATEGORIES,
  SELECT_CATEGORY_ID,
  FETCH_RESTAURANT_PRODUCTS,
  TOGGLE_PRODUCT_MODAL,
  SELECT_PRODUCT,
};

export default appActions;
